"""The production image installs the runtime versions that CI tests (#139).

`requirements-runtime.lock` is the hashed runtime resolution installed by `deploy/Dockerfile`;
CI tests `requirements-dev.lock` (runtime plus test tools). The runtime lock is compiled with
the dev lock as a constraint, so every runtime package must carry the same version and hashes
in both locks, and both must cover exactly the declared direct requirements.
"""
import re
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

BACKEND = Path(__file__).resolve().parents[1]
DOCKERFILE = BACKEND.parent / "deploy" / "Dockerfile"
RUNTIME_LOCK = BACKEND / "requirements-runtime.lock"
DEV_LOCK = BACKEND / "requirements-dev.lock"

COMPILE_OPTIONS = "--allow-unsafe {extra}--generate-hashes --no-emit-index-url --output-file={out} --strip-extras {src}"
LOCK_COMMANDS = {
    "requirements-dev.lock": "pip-compile " + COMPILE_OPTIONS.format(
        extra="", out="requirements-dev.lock", src="requirements-dev.txt"),
    "requirements-runtime.lock": "pip-compile " + COMPILE_OPTIONS.format(
        extra="--constraint=requirements-dev.lock ", out="requirements-runtime.lock",
        src="requirements.txt"),
}


def _direct_requirements(path):
    """Requirements declared in `path` itself (`-r` includes are not followed)."""
    requirements = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line and not line.startswith("-"):
            requirements.append(Requirement(line))
    return requirements


def _parse_lock(path):
    """{name: (version, hashes, via sources)} for every pinned entry of a pip-compile lock."""
    entries = {}
    name = None
    for line in path.read_text().splitlines():
        pin = re.match(r"^([A-Za-z0-9._-]+)==(\S+)", line)
        if pin:
            name = canonicalize_name(pin[1])
            assert name not in entries, f"{path.name}: {name} pinned twice"
            entries[name] = (pin[2], set(), set())
        elif name and (digest := re.search(r"--hash=(\S+)", line)):
            entries[name][1].add(digest[1])
        elif name and (source := re.match(r"^\s+#\s+(?:via\s+)?(-[rc] \S+)", line)):
            entries[name][2].add(source[1])
    return entries


def _lock_command(path):
    match = re.search(r"^#\s+(pip-compile .+)$", path.read_text(), re.MULTILINE)
    return match[1] if match else None


@pytest.mark.parametrize("lock", LOCK_COMMANDS)
def test_lock_is_generated_by_the_documented_command(lock):
    path = BACKEND / lock
    assert "autogenerated by pip-compile with Python 3.12" in path.read_text()
    assert _lock_command(path) == LOCK_COMMANDS[lock]
    for name, (_, hashes, _) in _parse_lock(path).items():
        assert hashes, f"{lock}: {name} has no hashes"


@pytest.mark.parametrize(("lock", "source"), [
    ("requirements-runtime.lock", "requirements.txt"),
    ("requirements-dev.lock", "requirements.txt"),
    ("requirements-dev.lock", "requirements-dev.txt"),
])
def test_lock_pins_exactly_the_declared_requirements(lock, source):
    entries = _parse_lock(BACKEND / lock)
    declared = {canonicalize_name(r.name): r for r in _direct_requirements(BACKEND / source)}

    for name, requirement in declared.items():
        assert name in entries, f"{source} declares {name}; regenerate {lock}"
        assert requirement.specifier.contains(entries[name][0], prereleases=True), (
            f"{lock} pins {name}=={entries[name][0]}, {source} requires {requirement}")
    from_source = {name for name, (_, _, via) in entries.items() if f"-r {source}" in via}
    assert from_source == set(declared), f"{lock} is stale for {source}; regenerate it"


def test_dev_requirements_include_the_runtime_requirements():
    assert "-r requirements.txt" in (BACKEND / "requirements-dev.txt").read_text().splitlines()


def test_runtime_lock_matches_the_tested_dev_lock():
    runtime = _parse_lock(RUNTIME_LOCK)
    dev = _parse_lock(DEV_LOCK)

    assert set(runtime) <= set(dev), f"runtime-only packages: {sorted(set(runtime) - set(dev))}"
    for name, (version, hashes, _) in runtime.items():
        assert version == dev[name][0], f"{name}: runtime {version}, tested {dev[name][0]}"
        assert hashes == dev[name][1], f"{name}: runtime and dev lock hashes differ"
    test_only = set(dev) - set(runtime)
    assert {"pytest", "ruff"} <= test_only, "test tools must not be in the production lock"


def test_production_image_installs_only_the_runtime_lock():
    installs = [line for line in DOCKERFILE.read_text().splitlines()
                if re.search(r"\bpip\b.*\binstall\b", line)]
    assert installs, "no pip install in deploy/Dockerfile"
    for line in installs:
        assert "--require-hashes" in line and "requirements-runtime.lock" in line, line
        assert "requirements.txt" not in line, line
