"""Test-owned Weaviate store for integration and browser tests.

Tests never use the development or production Weaviate. They use an instance named by
the ``SEMANT_TEST_WEAVIATE_*`` variables, normally a throwaway container started by
``scripts/with-test-weaviate.sh`` (see ``make test-integration``).

Each run has its own ownership token (``SEMANT_TEST_STORE_TOKEN``, generated by the script
or set by the CI job). Before creating or deleting anything, ``claim_store`` positively
verifies that the instance belongs to the current run:

* an instance with no collections at all is claimed by writing a marker with the token;
* an instance whose marker holds the current token is owned by this run;
* anything else is refused: data without a marker (e.g. a development snapshot) and
  also a marker left by another run (different or missing token).

The application's collection names are fixed (``Chunks``, ``Tag``, ...) and some are also
used as reference names, so they cannot be prefixed per run. The run's namespace is the
whole dedicated instance instead; tests in one run use it one at a time.
"""
from __future__ import annotations

import ipaddress
import os
import socket
from dataclasses import dataclass
from typing import Mapping

import weaviate
from weaviate import WeaviateAsyncClient
from weaviate.classes.config import Configure, DataType, Property, ReferenceProperty
from weaviate.classes.query import Filter

from semant_demo.schemas import CollectionNames

MARKER_COLLECTION = "SemantTestStoreMarker"
MARKER_PURPOSE = "semant-automated-tests"
_NIL_UUID = "00000000-0000-0000-0000-000000000000"

ENV_HOST = "SEMANT_TEST_WEAVIATE_HOST"
ENV_REST_PORT = "SEMANT_TEST_WEAVIATE_REST_PORT"
ENV_GRPC_PORT = "SEMANT_TEST_WEAVIATE_GRPC_PORT"
ENV_TOKEN = "SEMANT_TEST_STORE_TOKEN"
# CI service containers are reached by a service host name instead of loopback.
ENV_ALLOW_NONLOCAL = "SEMANT_TEST_WEAVIATE_ALLOW_NONLOCAL"


class StoreUnavailable(RuntimeError):
    """No test Weaviate is configured or reachable. Integration tests fail, never skip."""


class StoreNotOwned(RuntimeError):
    """The configured instance holds data that this test infrastructure did not create."""


@dataclass(frozen=True)
class StoreEndpoint:
    host: str
    rest_port: int
    grpc_port: int
    token: str

    @classmethod
    def from_env(cls, environ: Mapping[str, str] | None = None) -> "StoreEndpoint":
        env = os.environ if environ is None else environ
        missing = [name for name in (ENV_HOST, ENV_REST_PORT, ENV_GRPC_PORT, ENV_TOKEN) if not env.get(name)]
        if missing:
            raise StoreUnavailable(
                f"{', '.join(missing)} not set. Run `make test-integration`, or start a "
                "throwaway Weaviate with scripts/with-test-weaviate.sh."
            )
        endpoint = cls(env[ENV_HOST], int(env[ENV_REST_PORT]), int(env[ENV_GRPC_PORT]), env[ENV_TOKEN])
        if env.get(ENV_ALLOW_NONLOCAL) != "1" and not _is_loopback(endpoint.host):
            raise StoreUnavailable(
                f"Test Weaviate host {endpoint.host!r} is not a loopback address. Set "
                f"{ENV_ALLOW_NONLOCAL}=1 only for a dedicated throwaway instance."
            )
        return endpoint

    def app_environ(self) -> dict[str, str]:
        """Settings that point the application at this instance."""
        return {
            "WEAVIATE_HOST": self.host,
            "WEAVIATE_REST_PORT": str(self.rest_port),
            "WEAVIATE_GRPC_PORT": str(self.grpc_port),
        }


def _is_loopback(host: str) -> bool:
    try:
        return all(ipaddress.ip_address(info[4][0]).is_loopback
                   for info in socket.getaddrinfo(host, None))
    except (socket.gaierror, ValueError):
        return False


async def connect(endpoint: StoreEndpoint) -> WeaviateAsyncClient:
    client = weaviate.use_async_with_custom(
        http_host=endpoint.host, http_port=endpoint.rest_port, http_secure=False,
        grpc_host=endpoint.host, grpc_port=endpoint.grpc_port, grpc_secure=False,
        # Skips the client's PyPI version lookup (and gRPC ping); readiness is checked below.
        skip_init_checks=True,
    )
    try:
        await client.connect()
        if not await client.is_ready():
            raise StoreUnavailable(f"Test Weaviate at {endpoint} is not ready.")
    except Exception as e:
        await client.close()
        if isinstance(e, StoreUnavailable):
            raise
        raise StoreUnavailable(f"Cannot connect to test Weaviate at {endpoint}: {e}") from e
    return client


async def claim_store(client: WeaviateAsyncClient, token: str) -> None:
    """Verify (or establish, on an empty instance) that the instance belongs to this run."""
    if not token:
        raise StoreNotOwned("An ownership token is required.")
    names = set((await client.collections.list_all(simple=True)).keys())
    if MARKER_COLLECTION in names:
        marker = client.collections.get(MARKER_COLLECTION)
        objects = (await marker.query.fetch_objects(limit=10)).objects
        if not any(o.properties.get("purpose") == MARKER_PURPOSE and o.properties.get("token") == token
                   for o in objects):
            raise StoreNotOwned(
                f"{MARKER_COLLECTION} exists but was not written by this run (token mismatch). "
                "Use a fresh throwaway instance (scripts/with-test-weaviate.sh)."
            )
        return
    if names:
        raise StoreNotOwned(
            "Refusing to use a Weaviate instance that holds data not created by the test "
            f"infrastructure (collections: {', '.join(sorted(names))}). Use a dedicated "
            "throwaway instance (scripts/with-test-weaviate.sh)."
        )
    await client.collections.create(
        MARKER_COLLECTION,
        properties=[
            Property(name="purpose", data_type=DataType.TEXT),
            Property(name="token", data_type=DataType.TEXT),
        ],
    )
    await client.collections.get(MARKER_COLLECTION).data.insert({"purpose": MARKER_PURPOSE, "token": token})


def _app_collections_in_drop_order(names: CollectionNames) -> list[str]:
    return [
        names.span_collection_name,
        names.chunks_collection_name,
        names.document_collection_name,
        names.tag_collection_name,
        names.user_collection_name,
    ]


async def drop_app_collections(client: WeaviateAsyncClient, names: CollectionNames, token: str) -> None:
    """Delete the application collections, after re-verifying ownership. Keeps the marker."""
    await claim_store(client, token)
    for name in _app_collections_in_drop_order(names):
        if await client.collections.exists(name):
            await client.collections.delete(name)


async def _app_schema(client: WeaviateAsyncClient, names: CollectionNames) -> dict:
    configs = await client.collections.list_all(simple=False)
    return {name: configs.get(name) for name in _app_collections_in_drop_order(names)}


async def reset_app_collections(
        client: WeaviateAsyncClient, names: CollectionNames, token: str, created: dict) -> None:
    """Leave the application collections empty, after re-verifying ownership.

    Deletes the objects and keeps the collections if their configuration still equals
    the one this run created (cached in ``created``; pass the same dict on every call).
    Otherwise (first call, a test dropped a collection, auto-schema added a property, ...)
    drops and recreates them. Recreating per test dominated the suite's runtime, and
    dropping a just-created collection can stall for ~20 s in Weaviate 1.34 (HNSW
    commit-log unregistration timeout).
    """
    await claim_store(client, token)
    if not created or await _app_schema(client, names) != created:
        await drop_app_collections(client, names, token)
        await create_app_schema(client, names)
        created.clear()
        created.update(await _app_schema(client, names))
        return
    for name in _app_collections_in_drop_order(names):
        await _delete_all_objects(client.collections.get(name))


async def _delete_all_objects(collection) -> None:
    """Delete every object of ``collection`` or raise; never loops without progress."""
    # delete_many removes at most QUERY_MAXIMUM_RESULTS objects per call, so repeat
    # until nothing matches.
    while True:
        result = await collection.data.delete_many(where=Filter.by_id().not_equal(_NIL_UUID))
        if result.failed:
            raise RuntimeError(
                f"Resetting {collection.name}: {result.failed} of {result.matches} deletions failed.")
        if not result.matches:
            break
        if not result.successful:
            raise RuntimeError(
                f"Resetting {collection.name} made no progress: {result.matches} objects matched, none deleted.")
    remaining = (await collection.aggregate.over_all(total_count=True)).total_count
    if remaining:
        raise RuntimeError(f"Resetting {collection.name} left {remaining} objects.")


async def create_app_schema(client: WeaviateAsyncClient, names: CollectionNames) -> None:
    """Create the application collections as the backend expects them.

    Mirrors the properties and references the backend reads and writes in the current
    deployed schema (docs/DATABASE.md); metadata-enrichment properties that no code path
    uses are omitted. Vectors are self-provided under the ``default`` name.
    """
    text, text_array, integer = DataType.TEXT, DataType.TEXT_ARRAY, DataType.INT
    vectors = Configure.Vectors.self_provided()

    await client.collections.create(
        names.user_collection_name,
        vector_config=vectors,
        properties=[
            Property(name="name", data_type=text),
            Property(name="user_id", data_type=text),
            Property(name="description", data_type=text),
            Property(name="color", data_type=text),
            Property(name="created_at", data_type=DataType.DATE),
            Property(name="updated_at", data_type=DataType.DATE),
            Property(name="owner", data_type=text),
            Property(name="shared_with", data_type=DataType.UUID_ARRAY),
        ],
    )
    await client.collections.create(
        names.tag_collection_name,
        vector_config=vectors,
        properties=[
            Property(name="tag_name", data_type=text),
            Property(name="tag_shorthand", data_type=text),
            Property(name="tag_color", data_type=text),
            Property(name="tag_pictogram", data_type=text),
            Property(name="tag_definition", data_type=text),
            Property(name="tag_examples", data_type=text_array),
            Property(name="collection_name", data_type=text),
        ],
        references=[ReferenceProperty(name="userCollection", target_collection=names.user_collection_name)],
    )
    await client.collections.create(
        names.document_collection_name,
        vector_config=vectors,
        properties=[
            Property(name="title", data_type=text),
            Property(name="subtitle", data_type=text),
            Property(name="public", data_type=DataType.BOOL),
            Property(name="documentType", data_type=text),
            Property(name="partNumber", data_type=text),
            Property(name="partName", data_type=text),
            Property(name="dateIssued", data_type=DataType.DATE),
            Property(name="yearIssued", data_type=DataType.NUMBER),
            Property(name="language", data_type=text),
            Property(name="publisher", data_type=text),
            Property(name="placeOfPublication", data_type=text),
            Property(name="seriesName", data_type=text),
            Property(name="seriesNumber", data_type=text),
            Property(name="edition", data_type=text),
            Property(name="author", data_type=text_array),
            Property(name="editors", data_type=text_array),
            Property(name="illustrators", data_type=text_array),
            Property(name="translators", data_type=text_array),
            Property(name="redaktors", data_type=text_array),
        ],
        references=[ReferenceProperty(name="collection", target_collection=names.user_collection_name)],
    )
    await client.collections.create(
        names.chunks_collection_name,
        vector_config=vectors,
        properties=[
            Property(name="text", data_type=text),
            Property(name="title", data_type=text),
            Property(name="order", data_type=integer),
            Property(name="language", data_type=text),
            Property(name="start_page_id", data_type=text),
            Property(name="from_page", data_type=integer),
            Property(name="to_page", data_type=integer),
            Property(name="end_paragraph", data_type=DataType.BOOL),
        ],
        references=[
            ReferenceProperty(name="document", target_collection=names.document_collection_name),
            ReferenceProperty(name=names.user_collection_link_name, target_collection=names.user_collection_name),
            ReferenceProperty(name="positiveTag", target_collection=names.tag_collection_name),
            ReferenceProperty(name="negativeTag", target_collection=names.tag_collection_name),
            ReferenceProperty(name="automaticTag", target_collection=names.tag_collection_name),
        ],
    )
    await client.collections.create(
        names.span_collection_name,
        vector_config=vectors,
        properties=[
            Property(name="start", data_type=integer),
            Property(name="end", data_type=integer),
            Property(name="type", data_type=text),
            Property(name="reason", data_type=text),
            Property(name="confidence", data_type=DataType.NUMBER),
        ],
        references=[
            ReferenceProperty(name="tag", target_collection=names.tag_collection_name),
            ReferenceProperty(name="text_chunk", target_collection=names.chunks_collection_name),
        ],
    )
