import { z } from 'zod'

// Response from backend has snake_case, we want to transform it to camelCase for frontend
const CollectionSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  user_id: z.string(),
  description: z.string().nullable(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  color: z.string()
}).transform((collection) => ({
  id: collection.id,
  name: collection.name,
  userId: collection.user_id,
  description: collection.description,
  createdAt: new Date(collection.created_at),
  updatedAt: new Date(collection.updated_at),
  color: collection.color
}))

// For list of collections, we can reuse the same schema and just wrap it in an array
const CollectionsSchema = z.array(CollectionSchema)

// Request body for creating a collection - we don't need id, user_id, created_at, updated_at as those are generated by backend
const PostCollectionSchema = z.object({
  name: z.string(),
  description: z.string().nullable(),
  color: z.string()
}).transform((collection) => ({
  name: collection.name,
  description: collection.description,
  color: collection.color
}))

// Request body for updating a collection - all fields are optional, but we still want to validate their types
const PatchCollectionSchema = z.object({
  name: z.string().optional(),
  description: z.string().nullable().optional(),
  color: z.string().optional()
})

export { CollectionSchema, CollectionsSchema, PostCollectionSchema, PatchCollectionSchema }
