id: "xandry12_RagGenerator_gemma_default"
name: "Standard/Basic RAG"
description: "Lightweight and fast RAG implementation using Gemma 3 12B with basic retrieval and conversation history support. Typically responds in English."
class_name: "RagGenerator"
params:
  model_type: "OPENAI"
  model_name: "google/gemma-3-12b-it"
  temperature: 0.0
  search_type : "hybrid"
  alpha: 0.5
  chunk_limit: 5