id: "xandry12_RagGenerator_openai_default"
name: "Standard/Basic RAG"
description: "Lightweight and fast RAG implementation using GPT-4o-mini with basic retrieval and conversation history support. Typically responds in English."
class_name: "RagGenerator"
params:
  model_type: "OPENAI"
  model_name: "gpt-4o-mini"
  temperature: 0.0
  search_type : "hybrid"
  alpha: 0.5
  chunk_limit: 5