services:
  topicer:
    hostname: topicer
    build:
      context: .
      dockerfile: ./Dockerfile.topicer
      target: server
      args:
        - NOW=${NOW}
        - BRANCH_NAME=main
    env_file:
      - path: .env
        required: true
    ports:
    - "127.0.0.1:8089:8089"
    networks:
      - semant_demo_test_topicer
      - semant_demo_embedder
      - semant_demo_test_database
    volumes:
    - './data:/app/data'
    restart: always
    command: "python run.py"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

networks:
  semant_demo_test_topicer:
    name: semant_demo_test_topicer
    driver: bridge
  semant_demo_test_database:
    name: semant_demo_test_database
    external: true
  semant_demo_embedder:
    name: semant_demo_embedder
    external: true