services:
  app:
    restart: unless-stopped
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
      args:
        - REPO=${REPO}
        - BRANCH=${BRANCH}
        - BACKEND_URL=${BACKEND_URL}
    env_file:
      - path: .env
        required: true
    volumes:
      - ${SQL_DB_PATH}/tasks.db:/app/tasks.db
    networks:
      - web
      - semant_demo_test_database
      - semant_demo_embedder
    labels:
      - traefik.enable=true
      - traefik.http.routers.${TEST_ROUTER_NAME}.rule=Host(`${TEST_SUBDOMAIN}`)
      - traefik.http.routers.${TEST_ROUTER_NAME}.entrypoints=websecure
      - traefik.http.services.${TEST_ROUTER_NAME}.loadbalancer.server.port=8000

networks:
  web:
    external: true
  semant_demo_test_database:
    name: semant_demo_test_database
    external: true
  semant_demo_embedder:
    name: semant_demo_embedder
    external: true
