services:
  weaviate:
    hostname: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.34.4
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50051:50051"
    volumes:
      - /mnt/ssd2/weaviate_semant:/var/lib/weaviate
    restart: always
    stop_grace_period: 120s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      DISK_USE_READONLY_PERCENTAGE: "95"
      DISK_USE_WARNING_PERCENTAGE: "50"
    mem_limit: 128g
    memswap_limit: 0g
    networks:
      - semant_demo_database

networks:
  semant_demo_database:
    name: semant_demo_database
    driver: bridge
