id: "xandry12_AdaptiveRagGenerator_ollama_default_multiquery_web_search_off"
name: "Adaptive RAG using Ollama with multi query without web search"
description: "RAG using Ollama's local model Gemma3:12b. It supports history between messages. It has problem with citations, it answers based on provided documents but sometimes will not cite."
class_name: "AdaptiveRagGenerator"
params:
  model_type: "OLLAMA"
  model_name: "gemma3:12b"
  temperature: 0.0
  search_type : "hybrid"
  alpha: 0.5
  chunk_limit: 5
  qt_strategy : "multi_query"
  max_retries : 3
  web_search_enabled : False
  metadata_extraction_allowed : True
  self_reflection : True