id: "xandry12_AdaptiveRagGenerator_openrouter_gpt51_web_search"
name: "Adaptive RAG using OpenAI GPT5.1 with multi query and web search."
description: "Adaptive RAG with GPT5.1 model. It supports history between messages and internet/web search using DuckDuckGo."
class_name: "AdaptiveRagGenerator"
params:
  model_type: "OPENROUTER"
  model_name: "gpt-5.1"
  temperature: 0.0
  search_type : "hybrid"
  alpha: 0.5
  chunk_limit: 5
  qt_strategy : "multi_query"
  max_retries : 3
  web_search_enabled : True
  metadata_extraction_allowed : True
  self_reflection : True